SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE users;
TRUNCATE TABLE roles;
TRUNCATE TABLE permissions;
TRUNCATE TABLE permission_role;
SET FOREIGN_KEY_CHECKS = 1;

-- XOA DATA RAG RAC TRUOC KHI TEST LAI (chay 1 lan)
-- SET FOREIGN_KEY_CHECKS = 0;
-- TRUNCATE TABLE document_chunks;
-- TRUNCATE TABLE documents;
-- SET FOREIGN_KEY_CHECKS = 1;